In [79]:
import numpy as np
import matplotlib.pyplot as plt
import pickle
import numpy.random as rd
import numpy.linalg as la
import scipy.spatial.distance as spd

## Pergunta 1

In [80]:
D = pickle.load(open('A48286_Q001_data.p', 'rb'))
X = D['dados']
y = D['trueClass']

### a) -> i.

In [102]:
# Médias
m0 = np.mean(X[:,y==0],axis=1)
m1 = np.mean(X[:,y==1],axis=1)
m2 = np.mean(X[:,y==2],axis=1)
m3 = np.mean(X[:,y==3],axis=1)
m4 = np.mean(X[:,y==4],axis=1)

In [82]:
# Distância de Manhattan
np.round(spd.cityblock(m0,m1),2)

np.float64(12.68)

In [83]:
# Distância de Cosseno
np.round(spd.cosine(m0,m2),2)

np.float64(1.34)

### b) ->  iv.

In [84]:
# Média classe 1
np.round(m1,2)

array([ 0.  , -4.24])

In [85]:
# Média classe 4
np.round(m4,2)

array([-4.22, -0.03])

### c) -> iv.

In [86]:
X.shape

(2, 2550)

In [87]:
# Probabilidade classe 2
print(round(y[y==2].shape[0]/2550,2))

0.18


In [88]:
# Matriz de covariância classe 3
np.round(np.cov(X[:,y==3]),2)

array([[1.34, 0.02],
       [0.02, 1.33]])

### d) -> iii.

In [89]:
# Matrizes de covariância
cov0 = np.cov(X[:,y==0])
cov1 = np.cov(X[:,y==1])
cov2 = np.cov(X[:,y==2])
cov3 = np.cov(X[:,y==3])
cov4 = np.cov(X[:,y==4])

In [90]:
# Produto matricial m1 cov4 m4
np.round(np.dot(m1.T,np.dot(cov4,m4)),2)

np.float64(0.28)

In [91]:
# Produto interno m0 m1
np.round(np.dot(m0,m1),2)

np.float64(-26.94)

In [92]:
# Determinante do produto matricial cov1 cov3
np.round(la.det(np.dot(cov1,cov3)),2)

np.float64(2.28)

In [96]:
# Produto cov1 m2
np.round(np.dot(cov1,m2),2)

array([5.49, 0.15])

## Save file

In [94]:
QD = pickle.load(open('A48286_Ficha0_Respostas.p', 'rb'))
# Pergunta 1
QD['Q001'][0,:] = np.array([1,0,0,0])
QD['Q001'][1,:] = np.array([0,0,0,1])
QD['Q001'][2,:] = np.array([0,0,0,1])
QD['Q001'][3,:] = np.array([0,0,1,0])

# Save
pickle.dump(QD, open('A48286_Ficha0_Respostas.p', 'wb'))

# Show data
pickle.load(open('A48286_Ficha0_Respostas.p', 'rb'))

{'Q001': array([[1., 0., 0., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'nome': 'Tomas Miguel Baptista de Matos',
 'numero': 'A48286'}