In [5]:
import pickle
import numpy as np
import matplotlib.pyplot as plt
import numpy.random as rd
import scipy.linalg as la
from scipy.linalg import sqrtm

## Pergunta 1

### a) -> ii.

In [8]:
X = np.array([[-4,-3,-6,5,4,1,1],
      [3,4,0,-2,-3,0,-3]])
y = np.array([0,0,0,1,1,1,1])

In [9]:
m0 = np.mean(X[:, y==0], axis=1)
m1 = np.mean(X[:, y==1], axis=1)

cov1 = np.cov(X[:, y==1])

In [10]:
np.dot(cov1,m0)

array([-20.75,   9.  ])

In [11]:
np.dot(cov1,m1)

array([13.6875, -6.75  ])

### b) -> iii.

In [12]:
X1 = X[:, y==1]

In [15]:
np.dot(X1, X1.T)

array([[ 43, -25],
       [-25,  22]])

In [16]:
np.cov(X[:, y==0])

array([[2.33333333, 3.16666667],
       [3.16666667, 4.33333333]])

### c) -> i.

In [17]:
np.dot(m0, m1)

np.float64(-16.583333333333332)

In [18]:
la.norm(m1)

3.400367627183861

## Pergunta 2

### a) -> ii.

In [27]:
D = pickle.load(open('A47467_Q002_data.p', 'rb'))
X = D['dados']
y = D['trueClass']

In [29]:
np.mean(X, axis=1)

array([1.72426537, 0.56956565])

In [30]:
np.cov(X)

array([[ 9.57358268,  2.60761806],
       [ 2.60761806, 10.7069483 ]])

### b) -> iii.

In [32]:
m0 = np.mean(X[:, y==0], axis=1)
m1 = np.mean(X[:, y==1], axis=1)
m2 = np.mean(X[:, y==2], axis=1)
m3 = np.mean(X[:, y==3], axis=1)

cov0 = np.cov(X[:, y==0])
cov1 = np.cov(X[:, y==1])
cov2 = np.cov(X[:, y==2])
cov3 = np.cov(X[:, y==3])

In [33]:
np.dot(m2.T,np.dot(cov2,m3))

np.float64(-7.7261091183903705)

In [34]:
la.det(np.dot(cov0,cov2))

np.float64(1.4214801546761269)

In [35]:
np.dot(m1,m3)

np.float64(0.15698527735524576)

In [36]:
np.dot(cov1,m2)

array([12.04027046,  4.36507868])

### c) -> ii.

In [37]:
X.shape

(2, 1800)

In [38]:
print(round(y[y==0.0].shape[0]/1800,2))
print(round(y[y==1.0].shape[0]/1800,2))
print(round(y[y==2.0].shape[0]/1800,2))
print(round(y[y==3.0].shape[0]/1800,2))

0.22
0.28
0.28
0.22


In [39]:
np.cov(X[:, y==2])

array([[ 1.02238663, -0.14522993],
       [-0.14522993,  1.27197219]])

### d) -> iii.

In [41]:
np.mean(X[:, y==3], axis=1)

array([-0.0202414 , -4.28441259])

In [42]:
np.mean(X[:, y==1], axis=1)

array([-0.08931856, -0.03621905])

## Pergunta 3

### a) -> iii.

In [61]:
cov = np.cov(X)

In [62]:
Ctmp = np.mean(X**2, axis=1)
Ctmp = Ctmp[:, np.newaxis]
Cx = np.dot(Ctmp, Ctmp.T)
Cx == cov

array([[False, False],
       [False, False]])

In [63]:
mx = np.mean(X, axis=0)
Ctmp = np.dot(X,X.T) / (X.shape[1]-1)
Cx = Ctmp - np.dot(mx, mx.T)
Cx == cov

array([[False, False],
       [False, False]])

In [64]:
mx = np.mean(X, axis=1)
Xn = (X.T-mx).T
Ctmp = np.dot(Xn, Xn.T)
Cx = Ctmp / (X.shape[1]-1)
Cx == cov

array([[ True,  True],
       [ True,  True]])

In [65]:
mx = np.mean(X, axis=1)
Xn = (X.T-mx).T
Ctmp = Xn * Xn.T
Cx = Ctmp / (X.shape[1]-1)
Cx == cov

ValueError: operands could not be broadcast together with shapes (2,1000) (1000,2) 

### b) -> ii.

In [76]:
rd.seed(123)
X = rd.randn(2, 10000000)

In [77]:
A = np.array([[7.10,1.42],[-7.10,1.42]])
m = np.array([5, -1])

In [78]:
Y = np.dot(A, (X.T-m).T)
print(np.mean(Y, axis=1))
print(np.cov(Y))

[-34.07739894  36.91667454]
[[ 52.44314041 -48.41631596]
 [-48.41631596  52.45383252]]


In [79]:
Y = np.dot(A,X)+m[:,np.newaxis]
print(np.mean(Y, axis=1))
print(np.cov(Y))

[ 5.00260106 -1.00332546]
[[ 52.44314041 -48.41631596]
 [-48.41631596  52.45383252]]
