In [186]:
import numpy as np
import pickle
import numpy.random as rd
import numpy.linalg as la
import scipy.spatial.distance as spd

## Pergunta 1

In [187]:
D = pickle.load(open('A48286_Q001_data.p', 'rb'))
X = D['dados']
y = D['trueClass']

In [188]:
m0 = np.mean(X[:, y==0], axis=1)
m1 = np.mean(X[:, y==1], axis=1)
m2 = np.mean(X[:, y==2], axis=1)
m3 = np.mean(X[:, y==3], axis=1)
m4 = np.mean(X[:, y==4], axis=1)

cov0 = np.cov(X[:, y==0])
cov1 = np.cov(X[:, y==1])
cov2 = np.cov(X[:, y==2])
cov3 = np.cov(X[:, y==3])
cov4 = np.cov(X[:, y==4])

### a) -> ii

In [189]:
# Distância de Manhattan entre média 2 e 3
np.round(spd.cityblock(m2,m3),2)

np.float64(12.76)

In [190]:
# Distância de Cosseno entre média 0 e 4
np.round(spd.cosine(m0,m4),2)

np.float64(1.97)

### b) -> iii

In [191]:
# Determinante do produto matriciall entre covariâncias 1 e 4
np.round(la.det(np.dot(cov1,cov4)),2)

np.float64(1.55)

In [192]:
# Produto matricial entre média 0 transposta, covariância 0 e média 3
np.round(np.dot(m0.T,np.dot(cov0,m3)),2)

np.float64(-13.05)

In [193]:
# Produto interno entre médias 0 e 2
np.round(np.dot(m0,m2),2)

np.float64(-0.05)

In [194]:
# Produto entre covâriancia 0 e média 2
np.round(np.dot(cov0,m2),2)

array([ 0.34, -5.64])

### c) -> iii

In [195]:
X.shape

(2, 2550)

In [196]:
# Probabilidade da classe 2
round(y[y==2].shape[0]/2550,2)

0.16

In [197]:
# Covariância 3
np.round(cov3,2)

array([[2.98, 1.48],
       [1.48, 2.99]])

### d) -> iii

In [198]:
# Média 4
np.round(m4,2)

array([-0.03, -0.01])

In [199]:
# Média 1
np.round(m1,2)

array([-3.33, -1.69])

## Pergunta 2

In [200]:
X = np.array([[-4,-4,-1,-2,4,2,3],
              [0,-1,0,0,-2,-4,-2]])
y = np.array([0,0,0,0,1,1,1])

m0 = np.mean(X[:,y==0], axis=1)
m1 = np.mean(X[:,y==1], axis=1)

### a) -> iii

In [201]:
# Produto interno entre média 0 e 1
np.round(np.dot(m0,m1),2)

np.float64(-7.58)

In [202]:
# Norma da média 1
np.round(la.norm(m1),2)

np.float64(4.01)

### b) -> ii

In [203]:
# Distância de Manhattan entre média 0 e 1
np.round(spd.cityblock(m0,m1),2)

np.float64(8.17)

In [204]:
# Distância de Cosseno entre média 0 e 1
np.round(spd.cosine(m0,m1),2)

np.float64(1.68)

## Save File

In [205]:
QD = pickle.load(open('A48286_Ficha1_Respostas.p', 'rb'))
# Pergunta 1
QD['Q001'][0,:] = np.array([0,1,0,0])
QD['Q001'][1,:] = np.array([0,0,1,0])
QD['Q001'][2,:] = np.array([0,0,1,0])
QD['Q001'][3,:] = np.array([0,0,1,0])

# Pergunta 2
QD['Q002'][0,:] = np.array([0,0,1,0])
QD['Q002'][1,:] = np.array([0,1,0,0])

# Save
pickle.dump(QD, open('A48286_Ficha1_Respostas.p', 'wb'))

# Show data
pickle.load(open('A48286_Ficha1_Respostas.p', 'rb'))

{'Q001': array([[0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.],
        [0., 0., 1., 0.]]),
 'Q002': array([[0., 0., 1., 0.],
        [0., 1., 0., 0.]]),
 'nome': 'Tomas Miguel Baptista de Matos',
 'numero': 'A48286'}