In [2]:
import numpy as np
import pickle
import numpy.random as rd
import numpy.linalg as la
import scipy.spatial.distance as spd
from sklearn.metrics import confusion_matrix
from sklearn.neighbors import NearestCentroid

## Pergunta 1

In [3]:
X = np.array([[4,4,3,6,7,5,7,5],
              [6,6,3,5,4,4,3,6]])
y = np.array([0,0,0,0,1,1,1,1])

### a) -> i

In [4]:
Xa = np.array([[0,2],
               [1,3]])

nc = NearestCentroid(metric='manhattan').fit(X.T, y)
ye = nc.predict(Xa.T)
ye

array([0, 0])

### b) -> iii

In [5]:
nc = NearestCentroid(metric='euclidean').fit(X.T, y)
ye = nc.predict(X.T)
confusion_matrix(y, ye)

array([[3, 1],
       [1, 3]])

### c) -> iv

In [6]:
from sklearn.metrics.pairwise import cosine_similarity

m0 = np.mean(X[:, y==0], axis=1)
m1 = np.mean(X[:, y==1], axis=1)

cosine_sim_D0 = cosine_similarity(X.T, m0.reshape(1, -1))
cosine_sim_D1 = cosine_similarity(X.T, m1.reshape(1, -1))

D_cosine = np.vstack((cosine_sim_D0.T, cosine_sim_D1.T))
ye_cosine = np.argmax(D_cosine, axis=0)

print("Matriz de Confusão (D_cosine):\n", confusion_matrix(y, ye_cosine))


Matriz de Confusão (D_cosine):
 [[3 1]
 [1 3]]


### d) -> iii

In [7]:
print(spd.cityblock(m0, m1))
print(round(spd.cosine(m0, m1),2))

2.5
0.03


## Pergunta 2

In [8]:
D = pickle.load(open('A48286_Q002_data.p', 'rb'))
y = D['trueClass']
ye = D['estClass']

In [9]:
cm = confusion_matrix(y, ye)
cm

array([[959, 211],
       [104, 526]])

### a) -> iv

In [14]:
TN = 959
FP = 211
FN = 104
TP = 526

print(round(TN/(TN+FP)*100,1))

print("Posição correta: ", round(np.sum(y==1)/y.shape[0]*100,1))
print("Posição errada: ", round(np.sum(y==1)/y.shape[0],1)*100)

82.0
Posição correta:  35.0
Posição errada:  40.0


### b) -> iv

In [11]:
print(cm)
print(TN)
print(TP)

[[959 211]
 [104 526]]
959
526


## Save file

In [12]:
QD = pickle.load(open('A48286_Ficha2_Respostas.p', 'rb'))
# Pergunta 1
QD['Q001'][0,:] = np.array([1,0,0,0]) # 1
QD['Q001'][1,:] = np.array([0,0,1,0]) # 3
QD['Q001'][2,:] = np.array([0,0,0,1]) # 4
QD['Q001'][3,:] = np.array([0,0,1,0]) # 3

# Pergunta 2
QD['Q002'][0,:] = np.array([0,1,0,0]) # 2
QD['Q002'][1,:] = np.array([0,0,0,1]) # 4

# Save
pickle.dump(QD, open('A48286_Ficha2_Respostas.p', 'wb'))

# Show data
pickle.load(open('A48286_Ficha2_Respostas.p', 'rb'))

{'Q001': array([[1., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 1., 0.]]),
 'Q002': array([[0., 1., 0., 0.],
        [0., 0., 0., 1.]]),
 'nome': 'Tomas Miguel Baptista de Matos',
 'numero': 'A48286'}